### ISSUE TITLE
Failed to create user for webserver! (477)

### ISSUE THREAD

**Issue by PabloDons** [tbsac/Jodel-Web-Interface#1] opened 2016-08-24 20:20 UTC
it simply says the request to the jodel api failed and doesn't go further than that. The API returned error description "Signed request expected" and http response code 477
Is there something I can do to help troubleshoot this?
I have made sure the requirements where met before testing.

**Comment by tbsac** [comment] 2016-08-25 07:21
Should be fixed now, the issue is that Jodel only allows to create users with the newest version of the App, I updated the hmac secret and the jodel version which should resolve the issue.

**Closed as completed by tbsac** 2016-08-25 07:21 UTC
